version: "3.9"

services:
  kali:
    image: bloatedkali4
    privileged: true
    ports:
      - "${HOST_PORT}:3022"  # SSH from host -> Kali
    networks:
      innet:
        ipv4_address: "${SUBSUBNET}.0.2"

  blue_lagoon:
    build: Blue_Lagoon
    restart: always

    environment:
      RABBITMQ_URI: ${RABBITMQ_URI}
      OPEN_AI_SECRET_KEY: ${OPENAI_API_KEY}
    volumes:
      - "./configurations:/configurations"
    networks:
      innet:
        ipv4_address: "${SUBSUBNET}.0.3"

networks:
  innet:
    driver: bridge
    ipam:
      config:
        - subnet: "${SUBSUBNET}.0.0/24"

